### ISSUE TITLE
initialization of replay buffer

### ISSUE THREAD

**Issue by zkengz** [mindspore-lab/mindrl#85]
the current version of initialization of replay buffer does not work for PriorityReplayBuffer.
Line 260 of the mindrl/mindspore_rl/core/msrl.py:
buffer = replay_buffer_type(
                sample_size, capacity, buffer_data_shapes, buffer_data_type
            )
however, PriorityReplayBuffer requires an additional parameter "alpha".

**Comment by WilfChen** [comment]
Thank you for your feedback
This issue has been fixed now and you can specify like this
```
 "replay_buffer": {
    "number": 1,
    "type": PriorityReplayBuffer,
    "params": {"alpha": 1.0, "capacity": 100000, "sample_size": 64},
},
```

By the way, `PriorityReplayBuffer` has passed the ut test but has not been used in any algorithm.
